spring:
  main:
    banner_mode: off

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-194-73-236.compute-1.amazonaws.com:5432/darboitrll1f8c
    username: udzveceepmkuvq
    password: 3d36da1911be1b9c617ca49d9f8450220714c38d3381e0f01ba8bf60483660cd

  jpa:
    show-sql: true
#    generate-ddl: false
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;

server:
  port: ${PORT:8080}
  error:
    include-binding-errors: always
    include-message: always