spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-194-73-236.compute-1.amazonaws.com:5432/darboitrll1f8c
    username: udzveceepmkuvq
    password: 3d36da1911be1b9c617ca49d9f8450220714c38d3381e0f01ba8bf60483660cd

  jpa:
    show-sql: false
#    generate-ddl: false
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;

  flyway: baseline-on-migrate = true

server:
  port: ${PORT:8080}
  error:
    include-binding-errors: always
    include-message: always

flyway:
  user: postgres
  password: root
  schemas: movie_schema
  url: jdbc:postgresql://localhost:5432/movie
  locations: classpath:db/migration