INSERT INTO users (id, nickname, email, password, role)
VALUES (1,'Рональд Рейнольдс', 'ronald.reynolds66@example.com',
        '$2a$08$F5rK18KV86WFOEOtUBXb3Odl53xlm2ww9FnJXHmEloIZyaCAaEo.W', 'ROLE_USER'),
       (2,'Дарлин Эдвардс', 'darlene.edwards15@example.com',
        '$2a$08$rQLJjrXs7m9JMYXOOJ2EvuJjmI7QXF1EEkGGSvT4OOSVdZGIXnLSC', 'ROLE_USER'),
       (3,'Габриэль Джексон', 'gabriel.jackson91@example.com',
        '$2a$08$6Zh8VHpP7JbDLZmrp4jHdOoNMzY6JZnRh8H7YUTWR6RgFvX4OAGYu', 'ROLE_USER'),
       (4,'Дэрил Брайант', 'daryl.bryant94@example.com', '$2a$08$7LKpqvWBr1tPsTesyCLdKOFSkxU4et.QwGp0z26rYw.56o938s1x6',
        'ROLE_USER'),
       (5,'Нил Паркер', 'neil.parker43@example.com', '$2a$08$yv2KThOepP9RR1uwvRL7Vuv0MXkZHtwcj31kEUYDUqjMj2OWkB.Ga',
        'ROLE_USER'),
       (11,'Трэвис Райт', 'travis.wright36@example.com', '$2a$08$CK3CbUWC3PS4NAhlThw0j.JtQpet7Eiwi7.peRI9OLVh26NvwB9wa',
        'ROLE_USER'),
       (6,'Амелия Кэннеди', 'amelia.kennedy58@example.com',
        '$2a$08$ap1NA5xjmqND2SCp7JlE.O1RBzgJlKJlk2tNgq./HOtmjZO18g7Ny', 'ROLE_USER'),
       (7,'Айда Дэвис', 'ida.davis80@example.com', '$2a$08$z0xInEFP/Ighzxr3pGGyRevDmFzacJTyItahfYci7xswnC4ry7KYK',
        'ROLE_USER'),
       (8,'Джесси Паттерсон', 'jessie.patterson68@example.com',
        '$2a$08$Ofysd/l25njZXur3uV6/6OkUQb1S3AXefMaWITC9nNoqx9wCOytRa', 'ROLE_USER'),
       (9,'Деннис Крейг', 'dennis.craig82@example.com', '$2a$08$Yo9p/GyEeW2gsUQObZsJrOAI6P5VEaFBUqp8TqXLxu4zoAqfs3P5O',
        'ROLE_USER');