name: Start npm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ubuntu:
    runs-on: ubuntu-latest 
    steps:
    - name: Build with Npm
      run: npm run build
            
    - name: start with Npm
      run: npm start